import "./globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} max-w-screen-2xl bg-stone-900 mx-auto`}
			>
        {/* Todo Turn this Navigation into a reusable component. */}
				<header className="w-full h-24 fixed z-50 py-4 max-w-screen-2xl">
					<nav className=" bg-neutral-800 h-full mx-auto rounded-full shadow-lg flex items-center px-12 justify-between">
						<div>
							<h3 className="text-white text-2xl font-bold">
								Side
								<span className="text-blue-500">Hustle</span>
							</h3>
						</div>
						<ul>
							<li className="font-semibold text-white hover:text-blue-500 transition-colors ease-in-out duration-300">
								<Link href="/login">Login</Link>
							</li>
						</ul>
					</nav>
				</header>
				{children}
			</body>
		</html>
	);
}
